mod_id=charmony-travel-journal
short_id=travel_journal
mod_version=1.11.0
maven_group=dev.charmony.travel_journal
archives_base_name=charmony-travel-journal
mod_name=Charmony Travel Journal
mod_description=A journal to record interesting places around the world. Compatible with vanilla servers such as Realms.
