# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.daemon=false

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.1
loader_version=0.17.2
loom_version=1.11-SNAPSHOT

# Dependencies
fabric_version=0.134.1+1.21.10

# TOML Library Versions
toml4j_version=0.7.2
tomlnc_version=3.6.5

# Other versions
java_version=21
pack_version=88

# Metadata
discord_link=https://discord.gg/wreAFNb6XZ
sources_link=https://github.com/svenhjoo/charmony
homepage_link=https://charmony.dev
license=MIT