pluginManagement {
    repositories {
        maven {
            url "https://maven.fabricmc.net"
        }
        maven {
            name = "Terraformers"
            url = "https://maven.terraformersmc.com/"
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'charmony'

// Add subprojects/modules here.
include 'mods:core', 'mods:api', 'mods:ambient_sounds', 'mods:travel_journal', 'mods:tweaks'